version: "3.8"

services:
  backend:
    container_name: foodfinder-backend
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: foodfinder
    ports:
      - "27017:27017"
    volumes:
      - ./docker/seed-mongodb.js:/docker-entrypoint-initdb.d/seed-mongodb.js
      - mongodb_data_container:/data/db

  application:
    container_name: foodfinder-application
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      HOST: "0.0.0.0"
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "100"
    command: "npm run dev"

volumes:
  mongodb_data_container:
