version: "3.8"

services:
  backend:
    container_name: foodfinder-backend
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: foodfinder
    ports:
      - "27017:27017"
    volumes:
      - ./docker/seed-mongodb.js:/docker-entrypoint-initdb.d/seed-mongodb.js
      - mongodb_data_container:/data/db

  application:
    container_name: foodfinder-application
    image: node:lts-alpine
    working_dir: /home/node/app
    ports:
      - "3000:3000"
    volumes:
      - ./foodfinder-application:/home/node/app
    depends_on:
      - backend
    environment:
      HOST: "0.0.0.0"
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "100"
    command: "npm run dev"
    tty: true
    user: "${MY_USER}"

volumes:
  mongodb_data_container:
